name: Build
on:
  workflow_dispatch:

jobs:
  build-kata-static-tarball-arm64:
    uses: ./.github/workflows/build-kata-static-tarball-arm64.yaml
    with:
      push-to-registry: no
      stage: release